steps:
  # Show the gcloud info and check if gcloud exists
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - gcloud config list --quiet
  # Check the Python version
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - python3 .cloud-build/CheckPythonVersion.py -q
  # Fetch full repo for diff purposes
  - name: gcr.io/cloud-builders/git
    args: [fetch, --unshallow, --quiet]
  # Create a virtual environment
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - python3 -m venv workspace/env
  # Install Python dependencies and run index generation script
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - |
      . workspace/env/bin/activate &&
      python3 notebooks/notebook_template_review.py --web --title -steps --desc --linkback --notebook-dir=notebooks/official
    env:
    - 'IS_TESTING=1'
timeout: 86400s
